### ISSUE TITLE
SBG Venue Deployment

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#108]
### SBG Venue Deployment
**Venue**: SBG
**Project**: development
**Venue identifier:** sbg/development

### Acceptance Criteria
- SPS deployment (Hysds or Airflow -  see dependencies SPS) 
- Data Bucket (DS)
- Data Collections (DS)
- Jupyter (ADS)
- SDAP (AS)
- Venue API Gateway (CS)
- Cognito groups, users (SBG)
- Lambda Authorizer (CS)

### Work Tickets

- [x] https://github.com/unity-sds/sbg-workflows/issues/12
- [x] https://github.com/unity-sds/unity-data-services/issues/298
- [x] https://github.com/unity-sds/unity-data-services/issues/299
- [x] https://github.com/unity-sds/unity-cs/issues/320
- [x] https://github.com/unity-sds/unity-cs/issues/321
- [x] https://github.com/unity-sds/unity-cs/issues/323

### Dependencies

- [ ] https://github.com/unity-sds/unity-project-management/issues/114

**Comment by GodwinShen** [comment]
@galenatjpl, @ngachung, @mcduffie, @jjacob7734 please create and/or link your work tickets that cover the acceptance criteria shown above

**Comment by galenatjpl** [comment]
@GodwinShen I added two work tickets for these above.
