### ISSUE TITLE
STAC Data Keys update

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#109]
### STAC Data Keys Updates

Currently we use STAC asset keys of "data", "metadata" and others. This disallows the usage of multiple "data" types as an asset, which breaks the SBG workflows that contain multiple data workflows. 

### Acceptance Criteria
- STAC asset key is not based on "data" or "metadata" - should be unique and not known ahead of time and based on filename
- STAC asset role is used to define data, metadata, etc. (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-roles )
- Ingest commands can ingest multiple "data" role types successfully
- stage-in supports "downloading-keys" and "downloading roles"
- unity-py properly supports asset role (https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#asset-roles )
- Existing Workflows are updated to use new stage-in/out containers
- Create validation STAC outputs from unity-py

- file a ticket with CMR to use the asset-role in their results"
### Work Tickets

- [x] https://github.com/unity-sds/unity-py/issues/67
- [x] https://github.com/unity-sds/unity-py/issues/69
- [x] https://github.com/unity-sds/unity-data-services/issues/287
- [x] https://github.com/unity-sds/unity-data-services/issues/288
- [x] https://github.com/unity-sds/unity-data-services/issues/293
- [x] https://github.com/unity-sds/unity-data-services/issues/296
- [x] https://github.com/unity-sds/app-pack-generator/issues/20
- [x] Update sample applicaiton template with updated unity-py version
- [x] re-produce application packages with updated 
- [x] https://github.com/nasa/Common-Metadata-Repository/issues/2045

### Dependencies

- [ ] TBD

### Risks

- [x] https://github.com/unity-sds/unity-project-management/issues/129

**Comment by mike-gangl** [comment]
Need to have a discussion with @rtapella and @ngachung on the timing of this release.

- Timing of deployment of DAPA Search result updates
- Timing of deployment of DAPA ingest updates
- Timing of availability of new Stage-in tasks
- Timing of availability of new Stage-out tasks
- Timing of availability of unity-py Stac utilities updates
- Update application packages with unity py updates, stage-in, out docker containers

**Comment by GodwinShen** [comment]
@ngachung which work tickets are associated with the acceptance criteria shown below?

- STAC asset key is not based on "data" or "metadata" - should be unique and not known ahead of time and based on filename
- Ingest commands can ingest multiple "data" role types successfully
- file a ticket with CMR to use the asset-role in their results"

**Comment by GodwinShen** [comment]
@mike-gangl is this something that you would do?  If so, I guess we should have a ticket for it if you don't already have one elsewhere: Existing Workflows are updated to use new stage-in/out containers

**Comment by GodwinShen** [comment]
@rtapella , @anilnatha do we have a ticket for this item yet?  "Create validation STAC outputs from unity-py". The work tickets listed here don't immediately look applicable to me, but that could just be my lack of understanding.

**Comment by rtapella** [comment]
Good question. I am not sure what that means exactly or who would do it. Does it mean testing that this works? (specifically taht tickets 67 and 69 in unity.py work, the first two checkboxes)

**Comment by GodwinShen** [comment]
@mike-gangl I'd love to hear your thoughts on this conversation, this is in regards to the token passing for STAC browser. Seems there is a fork in the road for either: (1) token generation method added to unity_py as a user-assist tool; (2) integrate with cognito login/authentication. I'm not sure the pros and cons of each and what work each option would require. What do you think?

**Comment by GodwinShen** [comment]
@mike-gangl what do we mean by the task "Create validation STAC outputs from unity-py"?  I don't know if this is something we need UI/UX to do or what.  Can you help clarify this one?

**Comment by mike-gangl** [comment]
Open question- how can we inform U-DS which file is the stac-json file to read metadat from. Consider the case where we have multiple metadata file ending with .json?

```
data_file.tiff (role: data)
data_file.met.json (role: metadata)
data_file.json (role: metadata, stac, u-ds needs this one)
data_file.mdf (role: metadata)
data_file.png (role: browse)
```

I wonder if we should call the file `data_file.stac.json` so we have a good indication of what to key off of?

@ngachung thoughts?

**Comment by ngachung** [comment]
We can standardize on data_file.stac.json, but for now our implementation as described in https://github.com/unity-sds/unity-data-services/issues/301 is to parse all the json files until we get a valid stac feature.

**Comment by mike-gangl** [comment]
@GodwinShen - regarding "Validation Outputs" means to work with U-DS to ensure the output files from to_stac() are valid from the U-DS perspective. This is for `stage-out` and the `ingestion` portions of stac.

**Comment by rtapella** [comment]
marked Done but never Closed
