### ISSUE TITLE
Airflow Development and Deployment

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#114]
### Airflow Development and Deployment

Develop and deploy Airflow into the development, test, and SBG venues 

### Acceptance Criteria
- deploy Airflow envrionments to venue-dev, venue-test, venue-ops and SBG-dev
- Expose Airflow UI and rest calls to users through API gateway or HTTPD
- create CWL operator task for airflow
- WPS-T wrapper for airflow (deploy, execute)
- demonstrate workflow executions (soundersips, SBG)

**Stretch AC:**
- stretch: integrate airflow with deployment marketplace
- stretch: enable node and pod scalability in airflow
- stretch: EBS disk usage

### Work Tickets
*Link to work tickets required to implement the epic*
- [x] https://github.com/unity-sds/unity-sps/issues/28
- [x] https://github.com/unity-sds/unity-sps/issues/32
- [x] https://github.com/unity-sds/unity-sps/issues/29
- [x] https://github.com/unity-sds/unity-sps/issues/31
- [x] https://github.com/unity-sds/unity-sps/issues/47
- [x] https://github.com/unity-sds/unity-sps/issues/48

### Dependencies
*Other epics or outside tickets required for this to work*
- [ ] TBC

### Associated Risks
*links to risk issues associated with this epic*
- [x] https://github.com/unity-sds/unity-project-management/issues/130

**Comment by GodwinShen** [comment]
@LucaCinquini please add and/or link your U-SPS work tickets to the acceptance criteria shown above.  If you only have a handful to do in the current sprint, adding those for now is probably okay.  It looks like you may have some tickets already in the queue (https://github.com/unity-sds/unity-sps-prototype/issues/255 and https://github.com/unity-sds/unity-sps-prototype/issues/269), so definitely add those ones in plus any additional ones that you identify as you go.

**Comment by LucaCinquini** [comment]
Here is the full SPS ticket board for this PI: 
https://github.com/orgs/unity-sds/projects/7/views/11

**Comment by GodwinShen** [comment]
Great, thanks!

**Comment by mike-gangl** [comment]
Closing as complete.
