### ISSUE TITLE
Set up sync meeting with U-DS and UI teams

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-project-management#132]
- STAC asset roles in unity-py
- how to test that things are working
- sync up dependencies (search?)

**Comment by rtapella** [comment]
Meeting is set for Jan 29 afternoon.

**Comment by mike-gangl** [comment]
Created a set of dependencies and work in each venue to get this to success. Put tentative dates on it (sprints) as well:

https://docs.google.com/spreadsheets/d/1owU3P3awzukRPqpVrqJx2OxHrbG32NCg1Gt5PGlF0uk/edit#gid=0
