### ISSUE TITLE
Review Airlfow Progress

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#134]
Risk mitigation work item. Review progress on tickets and functionality of workflow, including other risks.

**Comment by GodwinShen** [comment]
@LucaCinquini and @mike-gangl I would still like us to do this check-in, perhaps at next Tuesday's status meeting?

**Comment by LucaCinquini** [comment]
We can certainly provide an update on where we are next Tuesday.

**Comment by LucaCinquini** [comment]
SPS can provide a demonstration of the current Airflow capabilities during the Unity meeting next Tuesday.

**Comment by mike-gangl** [comment]
SPS deployment to dev and CWL workflow runs are partially successful. WPS-T will not be added by end of the PI, and will have to be a high priority 24.2 item.

**Comment by mike-gangl** [comment]
work is on progress, but we need to get the CWL workflows running and then push to venue-test, venue-prod, SBG-dev venues.
