### ISSUE TITLE
CWL Generation - Update to Output Parameter

### ISSUE THREAD

**Issue by brianlee731** [unity-sds/unity-project-management#200]
The output of stage-in process needs to be 'catalog.json' not 'stage-in-results.json'

Example: https://github.com/unity-sds/app-pack-generator/blob/main/app_pack_generator/templates/stage_in.cwl#L56

Screenshot:
![Image](https://github.com/user-attachments/assets/dcca4e1d-0cbc-444c-971e-5301c2b01fc5)

**Comment by ngachung** [comment]
stage-in writes a downloaded_feature_collection.json into the same download dir as all the data files and also dumps the content of it which we save to stage-in-results.json https://github.com/unity-sds/unity-data-services/blob/develop/cumulus_lambda_functions/stage_in_out/download_granules_abstract.py#L168-L173

1. We can rename the file from downloaded_feature_collection.json to catalog.json
2. Do we still need the outputBinding in CWL?

**Comment by mike-gangl** [comment]
it's not required from U-DS perspective, i don't think it's needed from any other needs.

**Comment by GodwinShen** [comment]
@wphyojpl has a PR in merge already.

**Comment by brianlee731** [comment]
Duplicate - ticket closed. Please see https://github.com/unity-sds/unity-data-services/issues/423 .
