### ISSUE TITLE
MMGIS integration into Unity Marketplace

### ISSUE THREAD

**Issue by galenatjpl** [unity-sds/unity-project-management#211]
### MMGIS Integration into Unity Marketplace

Allow users to deploy the MMGIS software via the Management Console, from a Marketplace item

### Acceptance Criteria
*Acceptance criteria required to implement the epic*
- TODO: fill this out

### Work Tickets
*Link to work tickets required to implement the epic*
- [x] https://github.com/unity-sds/unity-cs/issues/507
- [x] https://github.com/unity-sds/unity-cs/issues/394

### Dependencies
*Other epics or outside tickets required for this to work*
- [ ] TODO

### Associated Risks
*links to risk issues associated with this epic*
- [ ] TBC

**Comment by GodwinShen** [comment]
EC2 instance is stood up with Terraform, some permission issues that Alice ran in to.  Alice is circling back with Tariq on that.

**Comment by galenatjpl** [comment]
@jdrodjpl and I debugged (on 10/30) some final issues related to deployment via the Management Console.
@jdrodjpl tested again this morning (10/31), on a fresh MC installation, and the deployment was a success.  
Screenshot, showing the deployed app:
<img width="1970" alt="Screenshot 2024-10-31 at 1 40 18 PM" src="https://github.com/user-attachments/assets/6d331730-2a69-45d2-b4ac-b55f9a233ede">
So this can be considered a success!

**Comment by galenatjpl** [comment]
Implemented, and proven to work.  Will demo to MDPS team next week.
