### ISSUE TITLE
As a project Operator, i want large batch submissions to require a confirmation before being executed in the processing system.

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#40]
-Large (e.g. <TBD> workflows resulting in <TBD> jobs) require a user to confirm this submission to the system. 
-Threshhold for large is set at SPS deploy time 
- When the sum of the number of workflows submitted > TBD workflows (set at deploy time) or the sum of the number of jobs to be initiated by the set of workflows exceeds TBD jobs, the users request is saved, and a "confirmation" is requested from the user.
- The user can confirm the request and processing is started
- The user can ignore the request and the processing is not started
- The user can delete the request and the processing is removed
- if the request is ignore, it will be automatically purged after 72 hours (3 day weekend)

**Comment by rtapella** [comment]
Also see: https://github.com/MAAP-Project/job-etc

May be good to have a pre-flight estimate of time and/or cost and use that to trigger a confirmation... or if it's quick enough always display and estimate of time/cost by the submit button

Asking for the time/cost estimate would should probably be a part of unity.py
