### ISSUE TITLE
As an Operator, I can view the logfiles of a failed task to gain a better understanding of what went wrong

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#45]

**Comment by galenatjpl** [comment]
@mike-gangl As I see it there are probably two main ways to view logs of a failed task:
1). Through some SPS interface (EMS?)

**Comment by rtapella** [comment]
In the near term I don’t really have an opinion on how to do this.

Longer-term we should avoid going straight to whatever the implementation detail is (e.g. HySDS)… I think MAAP throws related stderr and stdout into a field that you can get via WPS. Ideally an operator can see the log/stderr/stdout info in the Job dashboard as part of the results.
