### ISSUE TITLE
As a project data user, I can retrieve a time series of a gridded product through the Unity shared data catalog endpoints (DAPA).

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#48]
integrate Time Series calls through DAPA endpoints. high level architecture for this can be found here: https://lucid.app/lucidchart/538bc24b-24de-4717-98bc-3e1f52a331f8/edit?invitationId=inv_0daa327b-ab9e-4e74-8361-6fce97569421&page=MgBFQgTIbtBp#

![Image](https://user-images.githubusercontent.com/59702631/226061692-1e5043da-a27a-4796-aeaf-e9703f18b870.png)

**Comment by jjacob7734** [comment]
@zx128 (Zhangfan) will be the lead for this feature (I don't have permissions to add assignees).  He will implement the Process Mapper component to interface between DAPA clients and SDAP running in MCP/EKS.

**Comment by jjacob7734** [comment]
SDAP DAPA API implemented and deployed to `Unity-Dev`, `Unity-Test`, and `Unity-Prod`.
