### ISSUE TITLE
As an operator, I want to monitor Batch submissions through the unity Science Data System

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#50]
monitoring means the propagation of workflow labels and the ability to view batch processing as a whole, individual workflows within the batch, and individual tasks within the workflow (e.g. drill down from the parent component to the child component).

**Comment by rtapella** [comment]
SPS + UI teams

**Comment by mike-gangl** [comment]
Need to discern how this is different than "Workflow monitoring" feature

**Comment by rtapella** [comment]
This is distinct in that it implements the monitoring of batches, not just jobs. This suggests some sort of aggregation/summary to keep track of job status at the level of an entire batch.

e.g.
phase 1 = monitor single job
status = running (etc.)

phase 2 = monitor batch of jobs
status = 3 queued, 4 running, 1 failed

**Comment by rtapella** [comment]
Requires job database and potentially logic on the server-side to view everything with a particular label (batch ID).

**Comment by rtapella** [comment]
- use Airflow UI
