### ISSUE TITLE
As an operator, I want to list workflows and filter them on various criteria

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#51]
Filters include (combinations allowed):

- list jobs with filter: Workflow name
- list jobs with filter: label
- list jobs with filter: submitter
- list jobs with filter: an updates within timerange (Start/stop)
- list jobs by parent job ID

**Comment by rtapella** [comment]
this means... Jobs ? (WPS)

vs. listing the Workflows themselves (App Catalog/Dockstore)

**Comment by rtapella** [comment]
- More detail captured in the work ticket: https://github.com/unity-sds/unity-jobs-ui/issues/4

**Comment by rtapella** [comment]
we can filter client-side right now, with anything that WPS-T gives us
