### ISSUE TITLE
As an operator, I want to be able to see the status of individual tasks that comprise a workflow

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#53]
* UIUX needs to build/update the UI to support it
* uiux adds the call to unity.py/ unity.js
* SPS needs to update the WPS-T endpoint being called to provide more information on sub-task status

**Comment by mike-gangl** [comment]
duplicate of #44

**Comment by rtapella** [comment]
removing from Project Board because it's just noise
