### ISSUE TITLE
As a Unity Project Manager, I want to know how much i'm spending on shared services.

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#55]
Similar to #54 but for shared services.

* Algorithm Catalog
* Data Catalog

**Comment by galenatjpl** [comment]
@mike-gangl I'm sure there is a way to do this, but I have some hesitations about how this would happen.  AWS reports cost for atomic units of resource (for example a single instance of a DynamoDB, or a S3 bucket, etc..).  I'm not sure if this is the case, but if multiple projects have entries in the same Data Catalog, for example, and that's hosted by a database, there might not be a clear way to divide the costs up.  However, perhaps the easy way is to simply divide the cost of a shared resource by the number of projects.  So if a database costs $5 per month, and there are 5 projects, then each project would pay $1.  I think these shared services are intended to be pretty light-weight (not hold the actual data, but just references and metadata), so this actually may be close to a fair thing to do.  Anyway, further strategy/discussion is needed here.

**Comment by mike-gangl** [comment]
agreed @galenatjpl , it's not my intention to _bill_ a project here, just to know how much the resource is costing us for a reporting point of view. If, say, the API Gateway or the data catalog become very expensive, we'd have to look into billing units for those

**Comment by mike-gangl** [comment]
This might be addressed in #54 because that has been made less venue specific and more about the work we need to get done. We will keep this open until we get to this, and close if we already did tag allocations.

**Comment by galenatjpl** [comment]
I marked this as "done" on the project board, since we have a solution (i.e. mostly #54) that allows for costing in a non-specific way using tags on the Kion dashboard, and we have proven that to work.

**Comment by galenatjpl** [comment]
closing
