### ISSUE TITLE
SounderSIPS Operator Venue - Unity-SounderSIPs-Operators-Test

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#56]
Create a venue for SounderSIPS Operators (GesDISC) called Unity-SounderSIPs-Operators-Test in MCP:

Deploy the following Venue Specific Components

* ADE
* SPS
* Access Dashboards
* Integrate with Unity-Test API Gateway
* Add users to cognito, enable access
* Data bucket(s)

**Comment by GodwinShen** [comment]
Are there any pre-reqs that the SounderSIPS folks need to meet before they can use this venue?  Do they need to get MCP accounts?  Are there any venue specific configurations/permissions/etc per user to enable them to access and utilize the services?

**Comment by mike-gangl** [comment]
we slipped this to 23.3 because of funding issues already; i think we should focus on the SounderSIPS test environment for most usage at this point.
