### ISSUE TITLE
Deploy to the Unity-SIPS-Test venue

### ISSUE THREAD

**Issue by mike-gangl** [unity-sds/unity-project-management#71]
Deploy capabilities to the unity-sips-test environment

Acceptance Criteria:
* SPS deployed
* API Gateway integration
* Cognito user groups created

**Comment by galenatjpl** [comment]
@mike-gangl I think we should make the title and description of this ticket clear that this is the "SPS Project account deployment to Unity-SIPS-Test, using Unity-Test shared services".

I think this deployment in 23.2 will be broken out into two main areas:

1. Manual Shared Services Account Deployments (It’s okay if these are not-automated for this release)
- Domain stuff setup for Unity-Prod (or Unity-Test)
- API Gateway deployment on shared services account (Unity-Prod).
- Mapping/routing between shared services and project API gateways (redirection based on “sips/test”) needs to be implemented.

2. Programmatic Deployment of project account (Unity-Prod) resources:
- API Gateway deploy
- EKS Deployment
- SPS Deployment
- API Gateway mapping of SPS routes
- SPS S3 bucket deployment

I think some details still need to be worked out by the SPS team, about how it can connect to DAPA or Data Catalog in Unity-Test.

**Comment by galenatjpl** [comment]
@mike-gangl  We should also be clear that the route from shared services API to the project API gateway works as part of the acceptance criteria here.
