### ISSUE TITLE
As an operator, I want to submit jobs via a GUI

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-project-management#72]
Web application to submit jobs . Phasing:

1. hard-coded single-CHIRP submission: https://github.com/unity-sds/unity-jobs-ui/issues/24
2. process-driven: https://github.com/unity-sds/unity-jobs-ui/issues/25
3. app-package driven: https://github.com/unity-sds/unity-jobs-ui/issues/26
4. Batch submission: #49 and https://github.com/unity-sds/unity-project-management/issues/39

**Comment by rtapella** [comment]
needs:
1. SPS: WPS-T endpoint
2. unity-py / unity-common-api : expose job submission
3. job submission ui

depends on general web app skeleton to be made also

**Comment by rtapella** [comment]
for FY23: at least be able to submit CHIRP rebinning jobs with a hard-coded set of parameters.

Ideal world: drive the parameters from a configuration (e.g. algorithmDescriptor.json)

**Comment by rtapella** [comment]
- works as a hard-coded form in 23.3

**Comment by rtapella** [comment]
check vs. Airflow

**Comment by rtapella** [comment]
we may also want to update the hard-coded jobs UI job-submission page with any SBG workflows

**Comment by mike-gangl** [comment]
I'd rather not re-open old issues when it's _new work_
