### ISSUE TITLE
Unity.py work for 23.3

### ISSUE THREAD

**Issue by rtapella** [unity-sds/unity-project-management#80]
Unity.py design doc
https://docs.google.com/document/d/1xI9qkzgHgjW7s_d1_o6oBMJ9f9jkpgYRleckCtoXoc4/edit

**Comment by mike-gangl** [comment]
What role do we see unity-py playing in 23.3?

**Comment by rtapella** [comment]
Well, there was a plan to make the common API and simplify the unity-py layer. At this point, based on the workload, the common API may not make it. Perhaps we could do part of it. Perhaps it's not the right approach (re: ElasticSearch API for the back-end??!). So in that case, unity-py would only be enhancements from the service areas (e.g. Dockstore stuff).
